#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(realpath "$0")")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${PROJECT_DIR}/.env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[setup]${NC} $*"; }
ok()    { echo -e "${GREEN}[  ok ]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $*"; }
fail()  { echo -e "${RED}[fail]${NC} $*"; exit 1; }

echo ""
echo "  ╔══════════════════════════════════╗"
echo "  ║       Rick AI — Setup           ║"
echo "  ╚══════════════════════════════════╝"
echo ""

# ==================== PHASE 1: DEPENDENCY CHECK ====================

info "Checking dependencies..."

command -v docker >/dev/null 2>&1 || fail "Docker not found. Install: https://docs.docker.com/engine/install/"
docker info >/dev/null 2>&1 || fail "Docker daemon not running. Start it: sudo systemctl start docker"
docker compose version >/dev/null 2>&1 || fail "Docker Compose plugin not found. Install: https://docs.docker.com/compose/install/"

ok "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+') + Compose $(docker compose version --short)"

# Check if port 80 is available (skip if Rick is already running)
WEB_PORT="${WEB_PORT:-80}"
if ss -tlnp 2>/dev/null | grep -q ":${WEB_PORT} " && ! docker compose -f "${PROJECT_DIR}/docker-compose.yml" ps -q 2>/dev/null | grep -q .; then
  warn "Port ${WEB_PORT} is in use. Set WEB_PORT in .env to use a different port."
fi

# ==================== PHASE 2: .ENV GENERATION ====================

if [[ -f "$ENV_FILE" ]]; then
  info ".env already exists — skipping generation"
  info "Edit ${ENV_FILE} to change settings"
  # Load existing values for the summary at the end
  WEB_PASSWORD=$(grep -oP '^WEB_AUTH_PASSWORD=\K.+' "$ENV_FILE" 2>/dev/null || echo "")
  WEB_PORT=$(grep -oP '^WEB_PORT=\K.+' "$ENV_FILE" 2>/dev/null || echo "80")
else
  info "Generating .env configuration..."
  echo ""

  # Gemini API key (required)
  echo -e "  ${CYAN}Gemini API Key${NC} (required)"
  echo ""
  echo "  Rick uses Google Gemini as its main LLM. You need a free API key."
  echo ""
  echo "  How to get one:"
  echo "    1. Go to https://aistudio.google.com/apikey"
  echo "    2. Sign in with your Google account"
  echo "    3. Click \"Create API key\""
  echo "    4. Copy the key and paste it below"
  echo ""
  GEMINI_KEY=""
  while [[ -z "$GEMINI_KEY" ]]; do
    read -rp "  Gemini API key: " GEMINI_KEY
    [[ -z "$GEMINI_KEY" ]] && warn "Gemini API key is required to run Rick."
  done
  ok "Gemini API key set"

  # Web UI password (optional but recommended)
  echo ""
  echo -e "  ${CYAN}Web UI Password${NC} (recommended)"
  echo ""
  echo "  The Web UI gives you a browser-based admin panel with:"
  echo "    - Chat interface with audio and image support"
  echo "    - User management (approve/block users)"
  echo "    - Sub-agent session viewer"
  echo "    - Settings, OAuth, and WhatsApp management"
  echo ""
  echo "  Pick any password you want. Leave empty to disable the Web UI."
  echo ""
  read -rp "  Web UI password: " WEB_PASSWORD
  if [[ -n "$WEB_PASSWORD" ]]; then
    ok "Web UI enabled"
  else
    warn "Web UI disabled (no password set)"
  fi

  # Database (optional)
  echo ""
  echo -e "  ${CYAN}PostgreSQL Database${NC} (optional)"
  echo ""
  echo "  Rick can use PostgreSQL or SQLite for storing memories and conversations."
  echo "  SQLite works out of the box (zero setup, stored at ./data/rick.db)."
  echo "  PostgreSQL is recommended for production (multi-user, better search)."
  echo ""
  echo "  Format: postgresql://user:password@host:5432/dbname"
  echo ""
  read -rp "  PostgreSQL URL (leave empty for SQLite): " DB_URL
  if [[ -n "$DB_URL" ]]; then
    ok "PostgreSQL configured"

    echo ""
    echo -e "  ${CYAN}pgvector Database${NC} (optional)"
    echo ""
    echo "  Semantic memory uses pgvector to search past conversations by meaning."
    echo "  Requires a PostgreSQL instance with the pgvector extension installed."
    echo "  Can be the same or a different database from the main one."
    echo ""
    read -rp "  pgvector URL (leave empty to skip): " VECTOR_DB_URL
    if [[ -n "$VECTOR_DB_URL" ]]; then
      ok "pgvector configured"
    fi
  else
    ok "Using SQLite (zero setup)"
    VECTOR_DB_URL=""
  fi

  # Encryption key (optional)
  echo ""
  echo -e "  ${CYAN}Memory Encryption Key${NC} (optional)"
  echo ""
  echo "  Rick can encrypt sensitive memories (passwords, tokens, credentials)"
  echo "  at rest using AES-256-GCM. Without this, they're stored as plaintext."
  echo ""
  echo "  Use any passphrase you want, or generate one:"
  echo "    openssl rand -base64 32"
  echo ""
  read -rp "  Encryption key (leave empty for plaintext): " ENCRYPTION_KEY
  if [[ -n "$ENCRYPTION_KEY" ]]; then
    ok "Memory encryption enabled"
  else
    warn "Credentials will be stored as plaintext"
  fi

  # Generate .env
  cat > "$ENV_FILE" <<ENVEOF
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M')

# === LLM Providers ===
GEMINI_API_KEY=${GEMINI_KEY}
GEMINI_MODEL=gemini-3-flash-preview

ANTHROPIC_API_KEY=
ANTHROPIC_MODEL=claude-opus-4-6

OPENAI_API_KEY=
OPENAI_MODEL=gpt-5.3-codex

# === Database ===
$(if [[ -n "$DB_URL" ]]; then echo "DATABASE_URL=${DB_URL}"; else echo "# DATABASE_URL="; fi)
$(if [[ -n "$VECTOR_DB_URL" ]]; then echo "VECTOR_DATABASE_URL=${VECTOR_DB_URL}"; else echo "# VECTOR_DATABASE_URL="; fi)

# === Web UI ===
$(if [[ -n "$WEB_PASSWORD" ]]; then echo "WEB_AUTH_PASSWORD=${WEB_PASSWORD}"; else echo "# WEB_AUTH_PASSWORD="; fi)
WEB_PORT=80

# === Agent ===
AGENT_LANGUAGE=pt-BR
MAX_MEMORY_ITEMS=1000
CONVERSATION_HISTORY_LIMIT=20

# === Security ===
$(if [[ -n "$ENCRYPTION_KEY" ]]; then echo "MEMORY_ENCRYPTION_KEY=${ENCRYPTION_KEY}"; else echo "# MEMORY_ENCRYPTION_KEY="; fi)

# === Monitoring ===
LOG_LEVEL=info
ENVEOF

  ok ".env created at ${ENV_FILE}"
fi

# ==================== PHASE 3: BUILD ====================

echo ""
info "Building Docker image (this may take a few minutes on first run)..."
cd "$PROJECT_DIR"

if docker compose build 2>&1 | tail -1; then
  ok "Docker image built"
else
  fail "Docker build failed. Check the output above."
fi

# ==================== PHASE 4: SYSTEMD SERVICE ====================

echo ""
read -rp "  Install as systemd service (starts on boot)? [Y/n]: " INSTALL_SERVICE
INSTALL_SERVICE="${INSTALL_SERVICE:-Y}"

if [[ "$INSTALL_SERVICE" =~ ^[Yy]$ ]]; then
  bash "${SCRIPT_DIR}/setup-service.sh"
else
  info "Starting with docker compose (no systemd)..."
  docker compose up -d
fi

# ==================== PHASE 5: HEALTH CHECK ====================

echo ""
info "Waiting for Rick to start..."

HEALTHY=false
for i in $(seq 1 20); do
  sleep 2
  RESP=$(curl -sf "http://localhost:${WEB_PORT}/health" 2>/dev/null || echo "")
  if echo "$RESP" | grep -q '"status":"ok"'; then
    HEALTHY=true
    break
  fi
done

if [[ "$HEALTHY" == "true" ]]; then
  ok "Rick is running and healthy!"
else
  warn "Rick started but health check didn't pass yet. Check logs:"
  echo "  docker compose logs -f agent"
fi

# ==================== DONE ====================

echo ""
echo "  ╔══════════════════════════════════╗"
echo "  ║       Rick AI — Ready!          ║"
echo "  ╚══════════════════════════════════╝"
echo ""
echo "  Next steps:"
echo "    1. Pair WhatsApp:  docker compose logs -f agent  (scan QR code)"
if [[ -n "${WEB_PASSWORD:-}" ]]; then
  echo "    2. Open Web UI:     http://localhost:${WEB_PORT}"
  echo "       Password:        ${WEB_PASSWORD}"
fi
echo ""
echo "  Useful commands:"
echo "    docker compose logs -f agent     # follow logs"
echo "    docker compose restart agent     # restart"
echo "    docker compose down              # stop"
echo ""
