#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(realpath "$0")")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${PROJECT_DIR}/.env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

info()  { echo -e "${CYAN}[setup]${NC} $*"; }
ok()    { echo -e "${GREEN}[  ok ]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $*"; }
fail()  { echo -e "${RED}[fail]${NC} $*"; exit 1; }
step()  { echo -e "\n${BOLD}── Step $1 ──${NC}\n"; }

echo ""
echo "  ╔══════════════════════════════════╗"
echo "  ║       Rick AI — Setup           ║"
echo "  ╚══════════════════════════════════╝"
echo ""

# ─────────────────────────────────────────────────────────────────────
# Step 1: Dependencies
# ─────────────────────────────────────────────────────────────────────

step "1/5 — Dependencies"

command -v docker >/dev/null 2>&1 || fail "Docker not found. Install: https://docs.docker.com/engine/install/"
docker info >/dev/null 2>&1 || fail "Docker daemon not running. Start it: sudo systemctl start docker"
docker compose version >/dev/null 2>&1 || fail "Docker Compose plugin not found. Install: https://docs.docker.com/compose/install/"

ok "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+') + Compose $(docker compose version --short)"

# ─────────────────────────────────────────────────────────────────────
# Step 2: Configuration
# ─────────────────────────────────────────────────────────────────────

step "2/5 — Configuration"

if [[ -f "$ENV_FILE" ]]; then
  info ".env already exists — skipping"
  echo -e "  ${DIM}Edit ${ENV_FILE} to change settings${NC}"

  # Load existing values for summary
  WEB_PASSWORD=$(grep -oP '^WEB_AUTH_PASSWORD=\K.+' "$ENV_FILE" 2>/dev/null || echo "")
  WEB_PORT=$(grep -oP '^WEB_PORT=\K.+' "$ENV_FILE" 2>/dev/null || echo "80")
else
  WEB_PORT="80"

  # ── Web UI Password (recommended) ──

  echo ""
  echo -e "  ${BOLD}Web UI Password${NC} ${YELLOW}recommended${NC}"
  echo -e "  ${DIM}Enables the admin panel: chat, user management, settings, sessions${NC}"
  echo ""

  read -rp "  > Password (empty = no Web UI): " WEB_PASSWORD
  [[ -n "$WEB_PASSWORD" ]] && ok "Web UI enabled" || warn "Web UI disabled"

  # ── Database (optional) ──

  echo ""
  echo -e "  ${BOLD}Database${NC} ${DIM}optional${NC}"
  echo -e "  ${DIM}PostgreSQL for production, SQLite for dev/testing (zero setup)${NC}"
  echo -e "  ${DIM}Format: postgresql://user:pass@host:5432/dbname${NC}"
  echo ""

  read -rp "  > PostgreSQL URL (empty = SQLite): " DB_URL
  VECTOR_DB_URL=""
  if [[ -n "$DB_URL" ]]; then
    ok "PostgreSQL"
    echo ""
    echo -e "  ${BOLD}pgvector${NC} ${DIM}optional — semantic search over past conversations${NC}"
    echo -e "  ${DIM}Needs pgvector extension. Can be same or separate DB${NC}"
    echo ""
    read -rp "  > pgvector URL (empty = skip): " VECTOR_DB_URL
    [[ -n "$VECTOR_DB_URL" ]] && ok "pgvector enabled"
  else
    ok "SQLite (./data/rick.db)"
  fi

  # ── Encryption (optional) ──

  echo ""
  echo -e "  ${BOLD}Memory Encryption${NC} ${DIM}optional${NC}"
  echo -e "  ${DIM}AES-256-GCM for passwords/tokens stored in memory${NC}"
  echo -e "  ${DIM}Generate a key: openssl rand -base64 32${NC}"
  echo ""

  read -rp "  > Encryption key (empty = plaintext): " ENCRYPTION_KEY
  [[ -n "$ENCRYPTION_KEY" ]] && ok "Encryption enabled" || warn "Plaintext storage"

  # ── Write .env ──

  cat > "$ENV_FILE" <<ENVEOF
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M')

# === LLM Providers ===
# Gemini: get key at https://aistudio.google.com/apikey
GEMINI_API_KEY=
GEMINI_MODEL=gemini-3-flash-preview
ANTHROPIC_API_KEY=
ANTHROPIC_MODEL=claude-opus-4-6
OPENAI_API_KEY=
OPENAI_MODEL=gpt-5.3-codex

# === Database ===
$(if [[ -n "$DB_URL" ]]; then echo "DATABASE_URL=${DB_URL}"; else echo "# DATABASE_URL="; fi)
$(if [[ -n "$VECTOR_DB_URL" ]]; then echo "VECTOR_DATABASE_URL=${VECTOR_DB_URL}"; else echo "# VECTOR_DATABASE_URL="; fi)

# === Web UI ===
$(if [[ -n "$WEB_PASSWORD" ]]; then echo "WEB_AUTH_PASSWORD=${WEB_PASSWORD}"; else echo "# WEB_AUTH_PASSWORD="; fi)
WEB_PORT=${WEB_PORT}

# === Agent ===
AGENT_LANGUAGE=pt-BR
MAX_MEMORY_ITEMS=1000
CONVERSATION_HISTORY_LIMIT=20

# === Security ===
$(if [[ -n "$ENCRYPTION_KEY" ]]; then echo "MEMORY_ENCRYPTION_KEY=${ENCRYPTION_KEY}"; else echo "# MEMORY_ENCRYPTION_KEY="; fi)

# === Monitoring ===
LOG_LEVEL=info
ENVEOF

  ok ".env saved"
fi

# ─────────────────────────────────────────────────────────────────────
# Step 3: Build
# ─────────────────────────────────────────────────────────────────────

step "3/5 — Build"

info "Building Docker image..."
cd "$PROJECT_DIR"

if docker compose build 2>&1 | tail -1; then
  ok "Image built"
else
  fail "Build failed. Run 'docker compose build' to see full output."
fi

# ─────────────────────────────────────────────────────────────────────
# Step 4: Start
# ─────────────────────────────────────────────────────────────────────

step "4/5 — Start"

if [[ "$(uname -s)" == "Linux" ]] && command -v systemctl >/dev/null 2>&1; then
  read -rp "  Install as systemd service (auto-start on boot)? [Y/n]: " INSTALL_SERVICE
  INSTALL_SERVICE="${INSTALL_SERVICE:-Y}"

  if [[ "$INSTALL_SERVICE" =~ ^[Yy]$ ]]; then
    bash "${SCRIPT_DIR}/setup-service.sh"
  else
    info "Starting with docker compose..."
    docker compose up -d
  fi
else
  info "Systemd not available ($(uname -s)) — starting with docker compose..."
  docker compose up -d
fi

# ─────────────────────────────────────────────────────────────────────
# Step 5: Verify
# ─────────────────────────────────────────────────────────────────────

step "5/5 — Verify"

info "Waiting for health check..."

HEALTHY=false
for _ in $(seq 1 20); do
  sleep 2
  RESP=$(curl -sf "http://localhost:${WEB_PORT}/health" 2>/dev/null || echo "")
  if echo "$RESP" | grep -q '"status":"ok"'; then
    HEALTHY=true
    break
  fi
done

if [[ "$HEALTHY" == "true" ]]; then
  ok "Rick is healthy!"
else
  warn "Health check pending. Check: docker compose logs -f agent"
fi

# ─────────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────────

echo ""
echo "  ╔══════════════════════════════════╗"
echo "  ║       Rick AI — Ready!          ║"
echo "  ╚══════════════════════════════════╝"
echo ""

if [[ -n "${WEB_PASSWORD:-}" ]]; then
  echo -e "  ${BOLD}Web UI${NC}"
  echo "    URL:       http://localhost:${WEB_PORT}"
  echo "    Password:  ${WEB_PASSWORD}"
  echo ""
fi

echo -e "  ${BOLD}WhatsApp${NC}"
echo "    Pair:  docker compose logs -f agent  (scan QR code)"
echo ""
echo -e "  ${BOLD}Commands${NC}"
echo "    docker compose logs -f agent     # follow logs"
echo "    docker compose up -d             # start (picks up .env changes)"
echo "    docker compose down              # stop"
echo ""
